apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weather-map-frontend-secrets
  namespace: weather-map
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: weather-map-frontend-secrets
    creationPolicy: Owner
  data:
    - secretKey: VITE_API_URL
      remoteRef:
        key: eks/weather-map/frontend
        property: VITE_API_URL
