apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: weather-map
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weather-map-frontend-secrets
  namespace: weather-map
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: weather-map-frontend-secrets
    creationPolicy: Owner
  data:
    - secretKey: VITE_API_URL
      remoteRef:
        key: eks/weather-map/frontend
        property: VITE_API_URL
