apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - external-secret.yaml
  - configmap.yaml

images:
  - name: 030635936907.dkr.ecr.ap-southeast-1.amazonaws.com/weather-map-frontend
    newTag: latest
