apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weather-map-backend-secrets
  namespace: weather-map
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: weather-map-backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: WEATHER_API_KEY
      remoteRef:
        key: eks/weather-map/backend
        property: WEATHER_API_KEY
    - secretKey: WEATHER_PROVIDER
      remoteRef:
        key: eks/weather-map/backend
        property: WEATHER_PROVIDER
    - secretKey: PORT
      remoteRef:
        key: eks/weather-map/backend
        property: PORT
    - secretKey: FRONTEND_URL
      remoteRef:
        key: eks/weather-map/backend
        property: FRONTEND_URL
    - secretKey: NODE_ENV
      remoteRef:
        key: eks/weather-map/backend
        property: NODE_ENV
