apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weather-map-backend
  namespace: weather-map
  labels:
    app: weather-map-backend
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: weather-map-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
