apiVersion: v1
kind: Service
metadata:
  name: weather-map-backend
  namespace: weather-map
spec:
  selector:
    app: weather-map-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
