apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: argocd
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: git-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: eks/argocd-image-updater/git-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: eks/argocd-image-updater/git-credentials
        property: password
