apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: git-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: eks/argocd-image-updater/git-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: eks/argocd-image-updater/git-credentials
        property: password
