apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::030635936907:role/scg-demo-eks-external-secrets"
