apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-map-backend
  namespace: argocd
  annotations:
    # GitHub Actions will update image tags via repository_dispatch
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/theerawatzuz/terraform-eks-scg-demo.git
    targetRevision: main
    path: kubernetes/apps/weather-map/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-map
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-map-frontend
  namespace: argocd
  annotations:
    # GitHub Actions will update image tags via repository_dispatch
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/theerawatzuz/terraform-eks-scg-demo.git
    targetRevision: main
    path: kubernetes/apps/weather-map/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-map
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-map-namespace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/theerawatzuz/terraform-eks-scg-demo.git
    targetRevision: main
    path: kubernetes/apps/weather-map
    directory:
      include: namespace.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-map
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
