apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-map-backend
  namespace: argocd
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: backend=030635936907.dkr.ecr.ap-southeast-1.amazonaws.com/weather-map-backend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^[0-9a-f]{7}$|^latest$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/theerawatzuz/terraform-eks-scg-demo.git
    targetRevision: main
    path: kubernetes/apps/weather-map/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-map
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-map-frontend
  namespace: argocd
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: frontend=030635936907.dkr.ecr.ap-southeast-1.amazonaws.com/weather-map-frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^[0-9a-f]{7}$|^latest$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/theerawatzuz/terraform-eks-scg-demo.git
    targetRevision: main
    path: kubernetes/apps/weather-map/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-map
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-map-namespace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/theerawatzuz/terraform-eks-scg-demo.git
    targetRevision: main
    path: kubernetes/apps/weather-map
    directory:
      include: namespace.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-map
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
